version: 1
update_configs:
  - package_manager: "elixir:hex"
    directory: "/"
    default_assignees:
    - "alanvardy"
    update_schedule: "live"
    automerged_updates:
    - match: {dependency_type: "all", update_type: "all"}
  - package_manager: "javascript"
    directory: "/assets"
    update_schedule: "live"
    automerged_updates:
    - match: {dependency_type: "all", update_type: "all"}
