name: Cypress

on: push

jobs:
  test:
    runs-on: ubuntu-16.04

    services:
      db:
        image: postgres:11.6
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-mix-cypress-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-cypress-
      - uses: actions/cache@v1
        with:
          path: _build
          key: ${{ runner.os }}-build-cypress-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-cypress-
      - uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: 22.1.8
          elixir-version: 1.9.4
      - run: mix deps.get
      - run: cd assets && npm install && npm install cypress --save-dev && cd ..
      - run: npm run deploy --prefix ./assets
      - run: mix phx.digest
      - run: mix cypress.ci
